name: Create Android Signing Files
description: Create Android signing files from GitHub secrets.
inputs:
  keystore_base64:
    description: Base64-encoded Android upload keystore
    required: true
  store_password:
    description: Android keystore store password
    required: true
  key_password:
    description: Android key password
    required: true
  key_alias:
    description: Android key alias
    required: true
runs:
  using: composite
  steps:
    - name: Write signing files
      shell: bash
      env:
        KEYSTORE_BASE64: ${{ inputs.keystore_base64 }}
        STORE_PASSWORD: ${{ inputs.store_password }}
        KEY_PASSWORD: ${{ inputs.key_password }}
        KEY_ALIAS: ${{ inputs.key_alias }}
      run: |
        set -euo pipefail
        echo "$KEYSTORE_BASE64" | base64 --decode > android/upload-keystore.jks
        cat > android/key.properties <<EOF
        storePassword=$STORE_PASSWORD
        keyPassword=$KEY_PASSWORD
        keyAlias=$KEY_ALIAS
        storeFile=../upload-keystore.jks
        EOF
