name: Set Coverage Annotation
description: Emit GitHub annotation notice for line coverage from coverage/lcov.info
runs:
  using: composite
  steps:
    - name: Set annotation
      shell: bash
      run: |
        if [ ! -f coverage/lcov.info ]; then
          echo "::notice title=Code Coverage::No coverage file was generated."
          exit 0
        fi

        LINES_FOUND=$(awk -F: '/^LF:/{sum+=$2} END {print sum+0}' coverage/lcov.info)
        LINES_HIT=$(awk -F: '/^LH:/{sum+=$2} END {print sum+0}' coverage/lcov.info)

        if [ "$LINES_FOUND" -gt 0 ]; then
          LINE_PCT=$(awk "BEGIN {printf \"%.2f\", ($LINES_HIT/$LINES_FOUND)*100}")
        else
          LINE_PCT="0.00"
        fi

        echo "::notice title=Code Coverage::Line coverage: ${LINE_PCT}% (${LINES_HIT}/${LINES_FOUND})"
