name: Generate Coverage Summary
description: Generate and publish coverage summary from coverage/lcov.info
runs:
  using: composite
  steps:
    - name: Generate summary
      shell: bash
      run: |
        if [ ! -f coverage/lcov.info ]; then
          echo "No coverage file found at coverage/lcov.info" >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        LINES_FOUND=$(awk -F: '/^LF:/{sum+=$2} END {print sum+0}' coverage/lcov.info)
        LINES_HIT=$(awk -F: '/^LH:/{sum+=$2} END {print sum+0}' coverage/lcov.info)
        BRANCHES_FOUND=$(awk -F: '/^BRF:/{sum+=$2} END {print sum+0}' coverage/lcov.info)
        BRANCHES_HIT=$(awk -F: '/^BRH:/{sum+=$2} END {print sum+0}' coverage/lcov.info)

        if [ "$LINES_FOUND" -gt 0 ]; then
          LINE_PCT=$(awk "BEGIN {printf \"%.2f\", ($LINES_HIT/$LINES_FOUND)*100}")
        else
          LINE_PCT="0.00"
        fi

        if [ "$BRANCHES_FOUND" -gt 0 ]; then
          BRANCH_PCT=$(awk "BEGIN {printf \"%.2f\", ($BRANCHES_HIT/$BRANCHES_FOUND)*100}")
        else
          BRANCH_PCT="0.00"
        fi

        {
          echo "## Code Coverage Summary"
          echo ""
          echo "- Line coverage: ${LINE_PCT}% (${LINES_HIT}/${LINES_FOUND})"
          echo "- Branch coverage: ${BRANCH_PCT}% (${BRANCHES_HIT}/${BRANCHES_FOUND})"
        } >> "$GITHUB_STEP_SUMMARY"
